### ISSUE TITLE
Issues with file/character encoding

### ISSUE THREAD

**Issue by AetherCollective** [3D1T0R/PortableApps.com-DevelopmentToolkit#3]
I was editing the AppInfo using the toolkit and I was unable to switch from the Details Tab. A log was generated when I exited the toolkit.

DevelopmentToolkit.exe.log:
```python-traceback
Traceback (most recent call last):
  File "gui\frontend.pyo", line 44, in <lambda>
  File "gui\frontend.pyo", line 28, in set_page
  File "gui\pages\details.pyo", line 15, in leave
  File "gui\pages\details.pyo", line 190, in save
  File "validator\engine__init__.pyo", line 24, in decorate
  File "validator\engine__init__.pyo", line 151, in save
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 679: ordinal not in range(128)
Traceback (most recent call last):
  File "gui\frontend.pyo", line 39, in closeEvent
  File "gui\pages\details.pyo", line 15, in leave
  File "gui\pages\details.pyo", line 190, in save
  File "validator\engine__init__.pyo", line 24, in decorate
  File "validator\engine__init__.pyo", line 151, in save
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 679: ordinal not in range(128)
```

In case formatting is lost, http://pastebin.com/mBrsK2TW

**Edit:**
> Trimmed error log to show only 1 copy of each portion that's relevant to this issue.
[Full log still available via PasteBin.](http://pastebin.com/mBrsK2TW)
~3D1T0R

**Comment by AetherCollective** [comment]
It also wiped my existing AppInfo.ini to nothing but the base template with blank values. Had to restore from a backup.

**Comment by AetherCollective** [comment]
Found the issue. I had "©" in the description. Removing "©" fixed the app from crashing.

**Comment by 3D1T0R** [comment]
This is a known issue. I haven't had time to figure it out, but even if it can be avoided, this bug report is valid and should be open till we can fix it.
